from __future__ import annotations

import hashlib
import json
import math
import re
import secrets
import zipfile
from collections.abc import Iterable
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .extraction import markdown_fence
from .models import Artifact, Document, OutputMode, ProcessingOptions, SkipRecord, SourceSpec
from .security import safe_filename

MARKDOWN_SCHEMA = "automd.markdown.v1"
RAG_SCHEMA = "automd.rag.v1"


def build_artifacts(
    output_dir: Path,
    *,
    requested_name: str,
    documents: list[Document],
    skipped: list[SkipRecord],
    warnings: list[str],
    sources: list[SourceSpec],
    options: ProcessingOptions,
) -> list[Artifact]:
    output_dir.mkdir(parents=True, exist_ok=True)
    base = safe_filename(requested_name or (sources[0].label if sources else "automd-output"))
    base = re.sub(r"\.(md|zip)$", "", base, flags=re.IGNORECASE) or "automd-output"
    markdown = render_markdown(base, documents, sources, options)
    markdown_path = output_dir / f"{base}.md"
    markdown_path.write_text(markdown, encoding="utf-8", newline="\n")
    if options.output_mode == OutputMode.MARKDOWN:
        return [_artifact(markdown_path, "text/markdown")]

    chunks = build_chunks(documents, options)
    manifest = build_manifest(documents, skipped, warnings, sources, options, chunks)
    chunks_path = output_dir / "chunks.jsonl"
    chunks_path.write_text(
        "".join(
            json.dumps(chunk, ensure_ascii=False, separators=(",", ":")) + "\n" for chunk in chunks
        ),
        encoding="utf-8",
        newline="\n",
    )
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    zip_path = output_dir / f"{base}-rag.zip"
    with zipfile.ZipFile(
        zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6
    ) as archive:
        archive.write(markdown_path, arcname=markdown_path.name)
        archive.write(chunks_path, arcname=chunks_path.name)
        archive.write(manifest_path, arcname=manifest_path.name)
    return [_artifact(zip_path, "application/zip")]


def render_markdown(
    title: str,
    documents: list[Document],
    sources: list[SourceSpec],
    options: ProcessingOptions,
) -> str:
    generated = datetime.now(UTC).isoformat()
    metadata = {
        "schema": MARKDOWN_SCHEMA,
        "generated_at": generated,
        "document_count": len(documents),
        "sources": [
            {"id": source.id, "kind": source.kind, "label": source.label} for source in sources
        ],
    }
    parts = [
        f"<!-- automd: {json.dumps(metadata, ensure_ascii=False, separators=(',', ':'))} -->",
        "",
        f"# {title}",
        "",
        f"> Generated by Auto-MD 2.0 · {generated} · {len(documents)} documents",
    ]
    anchors = [_anchor(document) for document in documents]
    if options.include_toc and documents:
        parts.extend(["", "## Contents", ""])
        for document, anchor in zip(documents, anchors, strict=True):
            parts.append(f"- [`{_escape_inline(document.path)}`](#{anchor})")
    for document, anchor in zip(documents, anchors, strict=True):
        parts.extend(
            [
                "",
                "---",
                "",
                f'<a id="{anchor}"></a>',
                f"## `{_escape_inline(document.path)}`",
                "",
                _provenance(document),
                "",
                _document_body(document),
            ]
        )
    return "\n".join(parts).rstrip() + "\n"


def build_chunks(documents: list[Document], options: ProcessingOptions) -> list[dict[str, Any]]:
    chunks: list[dict[str, Any]] = []
    for document in documents:
        body = _document_body(document)
        segments = _segments(body)
        grouped = _group_segments(segments, options.chunk_target, options.chunk_overlap)
        heading_path: list[str] = []
        for index, text in enumerate(grouped):
            headings = re.findall(r"^(#{1,6})\s+(.+)$", text, flags=re.MULTILINE)
            if headings:
                level = len(headings[-1][0])
                heading_path = heading_path[: max(level - 1, 0)] + [headings[-1][1].strip()]
            digest_input = "\0".join(
                [document.source_id, document.path, "/".join(heading_path), str(index), text]
            ).encode("utf-8")
            chunk_id = hashlib.sha256(digest_input).hexdigest()[:24]
            chunk = {
                "schema": RAG_SCHEMA,
                "id": chunk_id,
                "text": text.strip(),
                "title": document.title,
                "source": {
                    "id": document.source_id,
                    "label": document.source_label,
                    "path": document.path,
                    "url": document.source_url,
                    "sha256": document.sha256,
                },
                "heading_path": heading_path.copy(),
                "language": document.language,
                "chunk_index": index,
                "token_estimate": estimate_tokens(text),
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
            }
            chunks.append(chunk)
    return chunks


def build_manifest(
    documents: list[Document],
    skipped: list[SkipRecord],
    warnings: list[str],
    sources: list[SourceSpec],
    options: ProcessingOptions,
    chunks: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "schema": RAG_SCHEMA,
        "generated_at": datetime.now(UTC).isoformat(),
        "settings": asdict(options),
        "sources": [asdict(source) for source in sources],
        "documents": [
            {
                "source_id": document.source_id,
                "path": document.path,
                "title": document.title,
                "media_type": document.media_type,
                "language": document.language,
                "url": document.source_url,
                "sha256": document.sha256,
                "warnings": document.warnings,
            }
            for document in documents
        ],
        "skipped": [asdict(record) for record in skipped],
        "warnings": warnings,
        "counts": {
            "sources": len(sources),
            "documents": len(documents),
            "chunks": len(chunks),
            "skipped": len(skipped),
            "warnings": len(warnings) + sum(len(document.warnings) for document in documents),
        },
    }


def estimate_tokens(text: str) -> int:
    pieces = re.findall(r"\w+|[^\w\s]", text, flags=re.UNICODE)
    return max(1, math.ceil(len(pieces) * 1.15)) if text else 0


def _document_body(document: Document) -> str:
    if document.content_kind == "markdown":
        return _shift_headings(document.content, 2)
    fence = markdown_fence(document.content)
    language = document.language or "text"
    return f"{fence}{language}\n{document.content.rstrip()}\n{fence}"


def _shift_headings(text: str, offset: int) -> str:
    def replace(match: re.Match[str]) -> str:
        level = min(6, len(match.group(1)) + offset)
        return f"{'#' * level} {match.group(2)}"

    return re.sub(r"^(#{1,6})\s+(.+)$", replace, text, flags=re.MULTILINE)


def _provenance(document: Document) -> str:
    values = [
        f"Source: **{document.source_label}**",
        f"Type: `{document.media_type}`",
        f"SHA-256: `{document.sha256}`",
    ]
    if document.source_url:
        values.insert(1, f"URL: {document.source_url}")
    return "> " + " · ".join(values)


def _anchor(document: Document) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", document.path.casefold()).strip("-")[:60] or "document"
    suffix = hashlib.sha256(f"{document.source_id}\0{document.path}".encode()).hexdigest()[:8]
    return f"{slug}-{suffix}"


def _escape_inline(value: str) -> str:
    return value.replace("`", "\\`")


def _segments(text: str) -> list[str]:
    lines = text.splitlines()
    segments: list[str] = []
    current: list[str] = []
    in_fence = False
    fence_marker = ""
    for line in lines:
        fence_match = re.match(r"^(`{3,}|~{3,})", line)
        if fence_match:
            marker = fence_match.group(1)
            if not in_fence:
                in_fence = True
                fence_marker = marker[0]
            elif marker[0] == fence_marker:
                in_fence = False
        if not in_fence and (not line.strip() or re.match(r"^#{1,6}\s+", line)):
            if current:
                segments.append("\n".join(current).strip())
                current = []
            if line.strip():
                segments.append(line.strip())
            continue
        current.append(line)
    if current:
        segments.append("\n".join(current).strip())
    return [segment for segment in segments if segment]


def _group_segments(segments: list[str], target: int, overlap: int) -> list[str]:
    expanded: list[str] = []
    maximum = int(target * 1.5)
    for segment in segments:
        if estimate_tokens(segment) <= maximum:
            expanded.append(segment)
        else:
            expanded.extend(_split_oversized(segment, maximum))
    groups: list[list[str]] = []
    current: list[str] = []
    current_tokens = 0
    for segment in expanded:
        segment_tokens = estimate_tokens(segment)
        if current and current_tokens + segment_tokens > target:
            groups.append(current)
            overlap_segments: list[str] = []
            overlap_tokens = 0
            for previous in reversed(current):
                if overlap_tokens >= overlap:
                    break
                overlap_segments.insert(0, previous)
                overlap_tokens += estimate_tokens(previous)
            current = overlap_segments
            current_tokens = overlap_tokens
        current.append(segment)
        current_tokens += segment_tokens
    if current:
        groups.append(current)
    return ["\n\n".join(group).strip() for group in groups if group]


def _split_oversized(segment: str, maximum: int) -> Iterable[str]:
    lines = segment.splitlines()
    if len(lines) > 1:
        bucket: list[str] = []
        tokens = 0
        for line in lines:
            line_tokens = estimate_tokens(line)
            if bucket and tokens + line_tokens > maximum:
                yield "\n".join(bucket)
                bucket, tokens = [], 0
            bucket.append(line)
            tokens += line_tokens
        if bucket:
            yield "\n".join(bucket)
        return
    words = segment.split()
    bucket = []
    for word in words:
        bucket.append(word)
        if estimate_tokens(" ".join(bucket)) >= maximum:
            yield " ".join(bucket)
            bucket = []
    if bucket:
        yield " ".join(bucket)


def _artifact(path: Path, media_type: str) -> Artifact:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return Artifact(
        id=secrets.token_urlsafe(12),
        name=path.name,
        media_type=media_type,
        path=path,
        size=path.stat().st_size,
        sha256=digest,
    )
